services:
  django:
    container_name: prepare_lms
    build: .
    volumes:
      - ./code:/code
    ports:
      - "8001:8000"  # Ubah port host dari 8000 ke 8001
    command: python manage.py runserver 0.0.0.0:8000
  postgres:
    container_name: prepare_db
    image: postgres:16
    environment:
      - POSTGRES_DB=simple_lms
      - POSTGRES_USER=simple_user
      - POSTGRES_PASSWORD=simple_password
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5552:5432"