# Generated by Django 5.1.4 on 2025-01-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0003_coursecontent_coursemember_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='video_url',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Disetujui'),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Rilis'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coursemember',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
