# Generated by Django 5.1.4 on 2025-01-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0005_course_max_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemember',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Selesai'),
        ),
    ]
